In [1]:
import numpy as np 
import pandas as pd

Numpy -> çok boyutlu dizilerin (arrays) oluşturulması ve manipüle edilmesi için kullanılan
temel araçları sağlar. Bu diziler üzerinde matematiksel işlemler yapılmasını sağlayan metodları ve fonksiyonları içerir.

Pandas -> veri manipülasyonu ve analizi için tasarlanmıştır ve özellikle veri çerçeveleri (dataframes) ve seriler (series) adı verilen veri yapılarını kullanır.
    DataFrame: DataFrame, satırlar ve sütunlar halinde düzenlenmiş, farklı türde verileri içeren iki boyutlu bir veri yapısıdır. Bir Excel elektronik tablosuna benzer, ancak çok daha esnek ve güçlüdür. DataFrame'lerde veri okumak, yazmak, sorgulamak, filtrelemek, birleştirmek, gruplamak, dönüştürmek ve görselleştirmek gibi çeşitli işlemler yapılabilir.  

    Series-> Series, tek boyutlu etiketlenmiş bir dizi veri yapısıdır. İndekslenmiş bir veri koleksiyonunu temsil eder ve Python'un liste veya dizilerine benzer bir yapıya sahiptir. Ancak, bir Series, verilere etiketler (indeksler) eklemek ve verilere isim vermek gibi ek özelliklere sahiptir.

Pandas, veri ön işleme, temizleme, dönüştürme ve analiz için bir dizi fonksiyon ve metod sağlar. Ayrıca, CSV, Excel, SQL veritabanları ve HTML gibi çeşitli veri kaynaklarından veri okuma ve yazma işlemlerini kolaylaştıran araçlar içerir.
veri analizi, keşifsel veri analizi (EDA), veri görselleştirme ve makine öğrenimi gibi uygulamalar için tercih edilir.

Matplotlib -> grafik çizme ve veri görselleştirme kütüphanesidir. Bilimsel ve mühendislik uygulamalarında sıklıkla kullanılan bir araç olan Matplotlib, yüksek kalitede çizimler oluşturmayı sağlar. Çeşitli grafik türlerini destekler, bunlar arasında çizgi grafikleri, scatter plotlar, bar grafikleri, histogramlar, pasta grafikleri, kutu grafikleri ve yüzey grafikleri gibi grafikler bulunur. Kullanıcılar, veri analizi sonuçlarını ve keşifsel veri analizi sonuçlarını görsel olarak temsil etmek ve analiz etmek için bu grafik türlerini kullanabilirler.


In [27]:
myList = [20,30,40]

In [28]:
type(myList)

list

In [29]:
np.array(myList) # kullanımı ile list tipindeki array verisini numpy array'e dönüşütürürüz.

array([20, 30, 40])

In [30]:
myNumpyArray = np.array(myList)
type(myNumpyArray)

numpy.ndarray

In [31]:
matrixListesi = [[1,2,3],[10,20,30],[100,200,300]] # liste içerisinde liste

In [32]:
matrixListesi[1]

[10, 20, 30]

In [33]:
matrixListesi[1][2]

30

In [34]:
type(matrixListesi)

list

In [35]:
np.array(matrixListesi)  # numpy tipinde array'e dönüştürdüğümüzde matrix şeklinde görünür.

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [36]:
x =list(range(1,10)) # 1-10 aralığında liste oluşturur 10 dahil değil.
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
type(x)

list

In [38]:
x=np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
type(x)

numpy.ndarray

In [40]:
np.arange(0,10,2) # (start,end,step)

array([0, 2, 4, 6, 8])

In [41]:
np.zeros(4)  # değeri 0 olan 4 elemanlı numpy dizisi oluşturur.   değeri 1 olan numpy dizisi için de np.ones(4) kullanılabilir.

array([0., 0., 0., 0.])

In [42]:
np.zeros((2,2)) # değeri 0 olan 2x2 boyutunda matrix dizisi oluşturur.

array([[0., 0.],
       [0., 0.]])

In [43]:
np.linspace(0,20,5)  # (start,stop,value_size)
# burada 0 ve 10 arasında (0-10 dahil) start ve stop değerleri başta ve sonda olacak şekilde value_size kadar bir array oluşturulur.
# ardından her bir veri arasında eşit uzaklıkta aralık olacak şekilde ayarlanır. 
# veriler kendi arasında eşit dağıtılır.

array([ 0.,  5., 10., 15., 20.])

In [47]:
# random
# random array
np.random.randn(3)  

array([1.20500047, 1.31891516, 0.14969598])

In [48]:
np.random.randn(2,2)

array([[ 2.40645323,  0.30351984],
       [-1.08942237, -0.73881533]])

In [88]:
# eğer tek bir değer döndürmek istersek
np.random.randint(0,10) # bir range belirlenir ve olarakta sayı oluşur.  0 dahil 10 hariç


9

In [89]:
np.random.randint(1,10,4) # array içerisinde 1 ile 10 arasında 1 dahil 10 hariç 4 adet dizi elemanı oluşturur.

array([7, 6, 1, 4])

In [104]:
myRandomArray = np.random.randint(0,50,20) 
myRandomArray

array([45, 43, 30, 33, 12, 24, 48, 15,  0, 21, 44, 28, 36,  0, 21, 45, 46,
        2,  6, 46])

In [106]:
myRandomArray.reshape(4,5)  # oluşturulan numpy array 4-5 boyutunda ayarlanır.

array([[45, 43, 30, 33, 12],
       [24, 48, 15,  0, 21],
       [44, 28, 36,  0, 21],
       [45, 46,  2,  6, 46]])

In [107]:
myRandomArray.max()

48

In [108]:
myRandomArray.min()

0

In [114]:
myRandomArray.argmax() # max elemanın bulunduğu index  -> 6
myRandomArray.argmin() # min elemanın bulunduğu index  -> 8

8

In [2]:
myArray = np.arange(0,15)
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
myNewArray = np.arange(0,30)
myNewArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
myNewArray[3:10]  # [include : not include]

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
mySlicingArray = myNewArray[3:10]

In [9]:
mySlicingArray

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
mySlicingArray[:] = 100  # bu array içerisindeki tüm değerleri 100 yap

In [11]:
mySlicingArray

array([100, 100, 100, 100, 100, 100, 100])

In [20]:
myNewArray    # numpy içerisinde ana array'de değişmektedir.

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [14]:
exampleArray = np.arange(0,30)
exampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
exampleCopyArray = exampleArray.copy()  #copy metodu ile ana array'in değerleri korunur.
exampleCopyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
slicingExampleCopyArray = exampleCopyArray[3:10]
slicingExampleCopyArray

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
slicingExampleCopyArray[:] = 200
slicingExampleCopyArray

array([200, 200, 200, 200, 200, 200, 200])

In [18]:
exampleCopyArray

array([  0,   1,   2, 200, 200, 200, 200, 200, 200, 200,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [19]:
exampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
newArray = np.random.randint(0,100,30)

In [23]:
newArray

array([34, 38, 37, 44, 93, 77, 86, 75, 53,  7, 21, 64, 69, 80, 88, 17,  1,
       56, 20, 18, 71, 60,  7, 29, 39, 70, 63, 47, 86,  6])

In [24]:
newArray > 34

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True, False, False,  True,
       False, False,  True,  True, False, False,  True,  True,  True,
        True,  True, False])

In [25]:
resultArray = newArray > 34
resultArray

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True, False, False,  True,
       False, False,  True,  True, False, False,  True,  True,  True,
        True,  True, False])

In [26]:
newArray[resultArray]

array([38, 37, 44, 93, 77, 86, 75, 53, 64, 69, 80, 88, 56, 71, 60, 39, 70,
       63, 47, 86])

In [27]:
np.sqrt(newArray)

array([5.83095189, 6.164414  , 6.08276253, 6.63324958, 9.64365076,
       8.77496439, 9.2736185 , 8.66025404, 7.28010989, 2.64575131,
       4.58257569, 8.        , 8.30662386, 8.94427191, 9.38083152,
       4.12310563, 1.        , 7.48331477, 4.47213595, 4.24264069,
       8.42614977, 7.74596669, 2.64575131, 5.38516481, 6.244998  ,
       8.36660027, 7.93725393, 6.8556546 , 9.2736185 , 2.44948974])